// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/works": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/works" | "/*";
  };
  "layout/MainLayout.tsx": {
    id: "layout/MainLayout";
    page: "/" | "/about" | "/works";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/works.tsx": {
    id: "routes/works";
    page: "/works";
  };
  "routes/404.tsx": {
    id: "routes/404";
    page: "/*";
  };
};